[programs.localnet]
flipper = "2q7fhNtQDSc4PkEwT8MU2L1GTLSWL3hLPx25ivrxcwPv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/knox/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
